name: Upload to S3 bucket
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install AWS CLI 
        run: |
          sudo apt update
          sudo apt install -y awscli 
      - name: Verify AWS CLI 
        run: aws --version